### ISSUE TITLE
Thread safety font.go

### ISSUE THREAD

**Issue by Xyaren** [tdewolff/canvas#13]
the font.go class is using a shared buffer `sfntBuffer` , resulting in errors when drawing in parallel:

```
2020/01/22 17:52:44 http: panic serving [::1]:54444: runtime error: index out of range [6] with length 0
goroutine 213 [running]:
net/http.(*conn).serve.func1(0xc0003c01e0)
	/home/tobias/sdk/go1.14beta1/src/net/http/server.go:1772 +0x139
panic(0x97f4e0, 0xc00044a100)
	/home/tobias/sdk/go1.14beta1/src/runtime/panic.go:973 +0x396
golang.org/x/image/font/sfnt.(*Font).LoadGlyph(0xc00014c420, 0x1048420, 0x3160000002a, 0x0, 0x0, 0x0, 0x203000, 0x203000, 0x203000)
	/home/tobias/go/pkg/mod/golang.org/x/image@v0.0.0-20191214001246-9130b4cfad52/font/sfnt/sfnt.go:1395 +0x486
github.com/tdewolff/canvas.FontFace.ToPath(0xc0001202e0, 0xc000238000, 0x4028b1c71c71c71d, 0x0, 0x2, 0xffffffff, 0x0, 0x0, 0x0, 0x3ff0000000000000, ...)
	/home/tobias/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20200117214846-bca5a8fd1980/fontface.go:292 +0x418
github.com/tdewolff/canvas.textSpan.ToPath(0xc0001202e0, 0xc000238000, 0x4028b1c71c71c71d, 0x0, 0x2, 0xffffffff, 0x0, 0x0, 0x0, 0x3ff0000000000000, ...)
	/home/tobias/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20200117214846-bca5a8fd1980/text.go:669 +0x154
github.com/tdewolff/canvas.(*Text).ToPaths(0xc0003a5920, 0xc0001fe500, 0xffffffff, 0x3ff0000000000000, 0xa767c0, 0x1072300, 0xa767e0)
	/home/tobias/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20200117214846-bca5a8fd1980/text.go:523 +0x5d8
github.com/tdewolff/canvas.(*Rasterizer).RenderText(0xc000358000, 0xc0003a5920, 0x3ff0000000000000, 0x0, 0x405c5ae33c678cf0, 0x0, 0x3ff0000000000000, 0x40566b8000000000)
	/home/tobias/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20200117214846-bca5a8fd1980/rasterizer.go:86 +0x43
github.com/tdewolff/canvas.(*Canvas).Render(0xc00058e720, 0xa80300, 0xc000358000)
	/home/tobias/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20200117214846-bca5a8fd1980/canvas.go:447 +0x2c3
github.com/tdewolff/canvas.(*Canvas).WriteImage(0xc00058e720, 0x4000000000000000, 0x4c7557)
	/home/tobias/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20200117214846-bca5a8fd1980/canvas.go:513 +0x2c7
main.main.func1(0xa7efc0, 0xc0003da460, 0xc0000fe100)
	/home/tobias/Projects/flussibanner/cmd/flussibanner-server/main.go:42 +0x133
net/http.HandlerFunc.ServeHTTP(0xc00012e9c0, 0xa7efc0, 0xc0003da460, 0xc0000fe100)
	/home/tobias/sdk/go1.14beta1/src/net/http/server.go:2012 +0x44
net/http.(*ServeMux).ServeHTTP(0x1046fc0, 0xa7efc0, 0xc0003da460, 0xc0000fe100)
	/home/tobias/sdk/go1.14beta1/src/net/http/server.go:2387 +0x1a5
net/http.serverHandler.ServeHTTP(0xc0001480e0, 0xa7efc0, 0xc0003da460, 0xc0000fe100)
	/home/tobias/sdk/go1.14beta1/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc0003c01e0, 0xa80040, 0xc000080000)
	/home/tobias/sdk/go1.14beta1/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
	/home/tobias/sdk/go1.14beta1/src/net/http/server.go:2933 +0x35c
```

**Comment by Xyaren** [comment]
If required I can give you access to my project.
I'm very new to go so this might be a user error.

**Comment by tdewolff** [comment]
Thanks, can you check if this solves it?

**Comment by Xyaren** [comment]
Thank you for the quick reply.

Unfortunately this does not fix the issue:
```
2020/01/22 21:31:31 http: panic serving [::1]:64831: runtime error: index out of range
goroutine 41 [running]:
net/http.(*conn).serve.func1(0xc000066000)
	C:/Users/tobix/sdk/go1.12.4/src/net/http/server.go:1769 +0x140
panic(0x926380, 0x10229b0)
	C:/Users/tobix/sdk/go1.12.4/src/runtime/panic.go:522 +0x1c3
golang.org/x/image/font/sfnt.(*Font).LoadGlyph(0xc00009ab00, 0xc000060a40, 0x31600000052, 0x0, 0x0, 0x0, 0x1c0d58, 0x8, 0x18)
	C:/Users/tobix/go/pkg/mod/golang.org/x/image@v0.0.0-20191214001246-9130b4cfad52/font/sfnt/sfnt.go:1395 +0x49c
github.com/tdewolff/canvas.FontFace.ToPath(0xc000005060, 0xc000060a00, 0x4028b1c71c71c71d, 0x0, 0x2, 0xffffffff, 0x0, 0x0, 0x0, 0x3ff0000000000000, ...)
	C:/Users/tobix/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20200122201335-28d2761e4f5a/fontface.go:292 +0x42e
github.com/tdewolff/canvas.textSpan.ToPath(0xc000005060, 0xc000060a00, 0x4028b1c71c71c71d, 0x0, 0x2, 0xffffffff, 0x0, 0x0, 0x0, 0x3ff0000000000000, ...)
	C:/Users/tobix/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20200122201335-28d2761e4f5a/text.go:669 +0x15b
github.com/tdewolff/canvas.(*Text).ToPaths(0xc000248460, 0x12c, 0x4024000000000000, 0x3feaf75eebdd7baf, 0x0, 0x4024000000000000, 0x0)
	C:/Users/tobix/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20200122201335-28d2761e4f5a/text.go:523 +0x607
github.com/tdewolff/canvas.(*Rasterizer).RenderText(0xc000216000, 0xc000248460, 0x3ff0000000000000, 0x0, 0x405c7ae33c678cf0, 0x0, 0x3ff0000000000000, 0x40604f8000000000)
	C:/Users/tobix/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20200122201335-28d2761e4f5a/rasterizer.go:86 +0x4a
github.com/tdewolff/canvas.(*Canvas).Render(0xc000142ba0, 0xa6f060, 0xc000216000)
	C:/Users/tobix/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20200122201335-28d2761e4f5a/canvas.go:447 +0x2ca
github.com/tdewolff/canvas.(*Canvas).WriteImage(0xc000142ba0, 0x4000000000000000, 0x4c6b84)
	C:/Users/tobix/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20200122201335-28d2761e4f5a/canvas.go:513 +0x2cb
main.main.func1(0xa6e020, 0xc0000a6000, 0xc0000e0100)
	C:/Users/tobix/IdeaProjects/flussibanner/cmd/flussibanner-server/main.go:29 +0x40
net/http.HandlerFunc.ServeHTTP(0x9d7a78, 0xa6e020, 0xc0000a6000, 0xc0000e0100)
	C:/Users/tobix/sdk/go1.12.4/src/net/http/server.go:1995 +0x4b
net/http.(*ServeMux).ServeHTTP(0x104ab20, 0xa6e020, 0xc0000a6000, 0xc0000e0100)
	C:/Users/tobix/sdk/go1.12.4/src/net/http/server.go:2375 +0x1dd
net/http.serverHandler.ServeHTTP(0xc0001044e0, 0xa6e020, 0xc0000a6000, 0xc0000e0100)
	C:/Users/tobix/sdk/go1.12.4/src/net/http/server.go:2774 +0xaf
net/http.(*conn).serve(0xc000066000, 0xa6eda0, 0xc000230480)
	C:/Users/tobix/sdk/go1.12.4/src/net/http/server.go:1878 +0x858
created by net/http.(*Server).Serve
	C:/Users/tobix/sdk/go1.12.4/src/net/http/server.go:2884 +0x2fb
```

**Comment by Xyaren** [comment]
I guess this is because I have my FontFamily defined like this: 

```
var robotoFont = loadRoboto()

func loadRoboto() *canvas.FontFamily {
	fontFamily := canvas.NewFontFamily("roboto")
	loadFamily(fontFamily, "./res/fonts/Roboto-Regular.ttf", canvas.FontRegular)
	loadFamily(fontFamily, "./res/fonts/Roboto-Bold.ttf", canvas.FontBold)
	return fontFamily
}
```

**Comment by tdewolff** [comment]
I see the problem, the font is shared for all HTTP requests (as it should be) but that means some clients might be requesting font data at the same time. I could add a mutex to lock it, but as the `sfnt` library will be replace in the future I've just added a quick fix. In the future the font data should be properly cached and reused. Let me know if that fixes it for you!
