### ISSUE TITLE
division-by-zero when rendering a text with a specific font

### ISSUE THREAD

**Issue by zpl-zak** [tdewolff/canvas#204]
Hi, we've recently updated our canvas dependency to the latest version (from 6566432) but have stumbled upon a text rendering issue. The attached font is causing a division-by-zero exception:

```
panic: runtime error: integer divide by zero

goroutine 1 [running]:
golang.org/x/image/vector.(*Rasterizer).fixedLineTo(0xc0002f96b0, 0x496100?, 0xc0?)
        /home/zak/go/pkg/mod/golang.org/x/image@v0.6.0/vector/raster_fixed.go:135 +0x4d9
golang.org/x/image/vector.(*Rasterizer).LineTo(0xc0000a97e8?, 0x0?, 0x0?)
        /home/zak/go/pkg/mod/golang.org/x/image@v0.6.0/vector/vector.go:191 +0x27
github.com/tdewolff/canvas.(*Path).ToRasterizer(0xc0000a97d0?, 0xc0002f96b0, 0x3fefffffffffffff)
        /home/zak/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20221230020303-9eb6d3934367/path.go:1942 +0x1ba
github.com/tdewolff/canvas/renderers/rasterizer.(*Rasterizer).RenderPath(0xc0002ec6c0, 0xc0000a97b8?, {{0xff, 0xff, 0xff, 0xff}, {0x0, 0x0, 0x0, 0x0}, ...}, ...)
        /home/zak/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20221230020303-9eb6d3934367/renderers/rasterizer/rasterizer.go:113 +0x505
github.com/tdewolff/canvas.(*Text).RenderAsPath(0xc0002ec660, {0x8e8970, 0xc0002ec6c0}, {{0x3ff0000000000000, 0x0, 0x0}, {0x0, 0x3ff0000000000000, 0x0}}, 0x3fefffffffffffff)
        /home/zak/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20221230020303-9eb6d3934367/text.go:1145 +0x40d
github.com/tdewolff/canvas/renderers/rasterizer.(*Rasterizer).RenderText(0x3ff0000000000000?, 0x0?, {{0x3ff0000000000000, 0x0, 0x0}, {0x0, 0x3ff0000000000000, 0x0}})
        /home/zak/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20221230020303-9eb6d3934367/renderers/rasterizer/rasterizer.go:128 +0x4b
github.com/tdewolff/canvas.(*Canvas).RenderTo(0xc000170660, {0x8e8970, 0xc0002ec6c0})
        /home/zak/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20221230020303-9eb6d3934367/canvas.go:706 +0x3cc
github.com/tdewolff/canvas/renderers/rasterizer.Draw(0xc000170660, 0x3fefffffffffffff, {0x8e7d10, 0xc71560})
        /home/zak/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20221230020303-9eb6d3934367/renderers/rasterizer/rasterizer.go:17 +0x14e
github.com/tdewolff/canvas/renderers.PNG.func1({0x8e6520, 0xc000151b88}, 0x242?)
        /home/zak/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20221230020303-9eb6d3934367/renderers/renderers.go:79 +0x39
github.com/tdewolff/canvas.(*Canvas).WriteFile(0xc0002f9e58?, {0x803ff7?, 0x0?}, 0xc0001707e0)
        /home/zak/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20221230020303-9eb6d3934367/canvas.go:724 +0x67
github.com/tdewolff/canvas/renderers.Write({0x803ff7, 0x13}, 0x0?, {0xc0002f9e58, 0x1, 0x1})
        /home/zak/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20221230020303-9eb6d3934367/renderers/renderers.go:30 +0x2d1
main.main()
        /home/zak/projs/canvas_bug/main.go:25 +0x29c
```

Upon further inspection, it appears the letter "O" produces NaN path elements which then cause this exception to be raised.

The following code will reproduce this issue with the font attached:

```go
package main

import (
	"github.com/tdewolff/canvas"
	"github.com/tdewolff/canvas/renderers"
)

func main() {
	// Create new canvas of dimension 100x100 mm
	c := canvas.New(920, 320)

	// Create a canvas context used to keep drawing state
	ctx := canvas.NewContext(c)

	font := canvas.NewFontFamily("helvetica")
	if err := font.LoadFontFile("Helvetica Bold.ttf", canvas.FontRegular); err != nil {
		panic(err)
	}

	face := font.Face(65.19, canvas.White, canvas.FontRegular, canvas.FontNormal)
	text := canvas.NewTextBox(face, "O", 200, 0, canvas.Left, canvas.Top, 0.0, 0.16)

	ctx.DrawText(0, 0, text)

	renderers.Write("getting-started.png", c, canvas.DPI(25.4))
}
```

[Helvetica Bold.zip](https://github.com/tdewolff/canvas/files/10950978/Helvetica.Bold.zip)

Let me know if you need more information.

**Comment by tdewolff** [comment]
Thanks for the report, this has been fixed!

**Comment by zpl-zak** [comment]
Unfortunately, while it does resolve the original issue, there are cases of panic: p0 == p2 with some fonts (the one above included). https://github.com/tdewolff/canvas/commit/05162c5a0146bf2d2eb2864e9d5e0a26afb32064#diff-f2e95681f5febcabf4882f88709075e6afb519f4ab965d3601fb21365f2ce479R638

**Comment by tdewolff** [comment]
Some subroutines may generate invalid (straight) cubic Beziers, this is now properly handled.
