### ISSUE TITLE
Panic in PDF rendering - unknown PDF type []pdf.pdfDict

### ISSUE THREAD

**Issue by supertxtnet** [tdewolff/canvas#237]
When changing the renderer from Gio to PDF I'm getting this panic. Everything was working fine with Gio. This appears to be triggered by the use of LinearGradients.

Version of canvas is v0.0.0-20230725155945-641901f69684

```
panic: unknown PDF type []pdf.pdfDict

goroutine 6 [running]:
github.com/tdewolff/canvas/renderers/pdf.(*pdfWriter).writeVal(0x822f60?, {0x7f6580?, 0xc00049c528?})
	/home/foo/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20230725155945-641901f69684/renderers/pdf/writer.go:224 +0x78d
github.com/tdewolff/canvas/renderers/pdf.(*pdfWriter).writeVal(0x822f60?, {0x822f60?, 0xc0000987e0?})
	/home/foo/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20230725155945-641901f69684/renderers/pdf/writer.go:181 +0xa1a
github.com/tdewolff/canvas/renderers/pdf.(*pdfWriter).writeVal(0x822f60?, {0x822f60?, 0xc000098690?})
	/home/foo/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20230725155945-641901f69684/renderers/pdf/writer.go:181 +0xa1a
github.com/tdewolff/canvas/renderers/pdf.(*pdfWriter).writeVal(0x822f60?, {0x822f60?, 0xc000098810?})
	/home/foo/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20230725155945-641901f69684/renderers/pdf/writer.go:181 +0xa1a
github.com/tdewolff/canvas/renderers/pdf.(*pdfWriter).writeVal(0x822f60?, {0x822f60?, 0xc000098540?})
	/home/foo/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20230725155945-641901f69684/renderers/pdf/writer.go:181 +0xa1a
github.com/tdewolff/canvas/renderers/pdf.(*pdfWriter).writeVal(0x822f60?, {0x822f60?, 0xc000098330?})
	/home/foo/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20230725155945-641901f69684/renderers/pdf/writer.go:181 +0xa1a
github.com/tdewolff/canvas/renderers/pdf.(*pdfWriter).writeVal(0xc00009c270?, {0x822f60?, 0xc00039dda0?})
	/home/foo/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20230725155945-641901f69684/renderers/pdf/writer.go:181 +0xa1a
github.com/tdewolff/canvas/renderers/pdf.(*pdfWriter).writeObject(0xc00009c270, {0x822f60, 0xc00039dda0})
	/home/foo/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20230725155945-641901f69684/renderers/pdf/writer.go:231 +0xf9
github.com/tdewolff/canvas/renderers/pdf.(*pdfPageWriter).writePage(0xc000180ea0, 0x1?)
	/home/foo/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20230725155945-641901f69684/renderers/pdf/writer.go:608 +0x5d3
github.com/tdewolff/canvas/renderers/pdf.(*pdfWriter).Close(0xc00009c270)
	/home/foo/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20230725155945-641901f69684/renderers/pdf/writer.go:458 +0x4b
github.com/tdewolff/canvas/renderers/pdf.(*PDF).Close(...)
	/home/foo/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20230725155945-641901f69684/renderers/pdf/pdf.go:70
main.run(0xc00025c600)
	/home/foo/git/svgcanvas/cmd/main.go:88 +0x56b
main.main.func1()
	/home/foo/git/svgcanvas/cmd/main.go:37 +0x65
created by main.main
	/home/foo/git/svgcanvas/cmd/main.go:26 +0x25
exit status 2
```

**Comment by tdewolff** [comment]
Linear gradients work fine for me when exporting PDFs. Can you post how to reproduce the error?

**Comment by tdewolff** [comment]
Still interested in seeing a reproducible test case to fix this bug, please re-open if you can still provide this ;-)
