### ISSUE TITLE
Bug found in path intersection code

### ISSUE THREAD

**Issue by aldernero** [tdewolff/canvas#313]
I ran into a panic while working on a [Sketchy](https://github.com/aldernero/sketchy) design, the following was the output:

This was version `github.com/tdewolff/canvas v0.0.0-20240826095051-d1ddae9379e3`

```
Path: len=7 data=M149.97877662049572 224.22916650766612L149.14433542817252 224.6037334161251L149.14433542817252 223.8545995838749L149.97877662049572 224.22916649233386L149.8025869371265 224.34320427693422L149.8025869371265 224.11512872306577z
Intersection 0: seg=(1,3) t=(0,1) pos=(149.9787766,224.2291665) dir=(155.8254736°,24.17452644°) tangent
Intersection 1: seg=(1,4) t=(9.263060508e-08,4.38702148e-07) pos=(149.9787765,224.2291665) dir=(155.8254736°,147.0872632°)
Intersection 2: seg=(1,5) t=(0.2111469148,0.153234845) pos=(149.8025869,224.3082552) dir=(155.8254736°,270°)
Intersection 3: seg=(3,5) t=(0.7888530852,0.846765155) pos=(149.8025869,224.1500778) dir=(24.17452644°,270°)
Intersection 4: seg=(3,6) t=(0.9999999074,0.9999995613) pos=(149.9787765,224.2291665) dir=(24.17452644°,32.91273678°)
Intersection 5: seg=(4,6) t=(0,1) pos=(149.9787766,224.2291665) dir=(147.0872632°,32.91273678°) tangent
panic: Bug found in path intersection code, please report on GitHub at https://github.com/tdewolff/canvas/issues with the path or paths that caused this panic.

goroutine 15 [running]:
github.com/tdewolff/canvas.pathIntersections(0xc000d44930, 0x0, 0x0, 0x0)
        /home/vernon/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20240826095051-d1ddae9379e3/path_intersection_util.go:617 +0x20f8
github.com/tdewolff/canvas.(*Path).Settle(0xc000d448a0, 0x2)
        /home/vernon/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20240826095051-d1ddae9379e3/path_intersection.go:172 +0x338
github.com/tdewolff/canvas.(*Path).Stroke(0xc000c833b0, 0x3fd0000000000000, {0xb92b60?, 0x1193d40?}, {0xb92ac0?, 0xf2e2c0?}, 0x3f9b17e4b17e4b18)
        /home/vernon/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20240826095051-d1ddae9379e3/path_stroke.go:605 +0x198
github.com/tdewolff/canvas/renderers/rasterizer.(*Rasterizer).RenderPath(0xc000468090, 0xc000c833b0?, {{{0x1e, 0x1e, 0x1e, 0xff}, {0x0, 0x0}, {0x0, 0x0}}, ...}, ...)
        /home/vernon/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20240826095051-d1ddae9379e3/renderers/rasterizer/rasterizer.go:84 +0x2f5
github.com/tdewolff/canvas.(*Canvas).RenderViewTo(0xc00054ace0, {0xb98650, 0xc000468090}, {{0x3ff0000000000000, 0x0, 0x0}, {0x0, 0x3ff0000000000000, 0x0}})
        /home/vernon/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20240826095051-d1ddae9379e3/canvas.go:826 +0x377
github.com/tdewolff/canvas.(*Canvas).RenderTo(...)
        /home/vernon/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20240826095051-d1ddae9379e3/canvas.go:811
github.com/tdewolff/canvas/renderers/rasterizer.Draw(0xc00054ace0, 0x400e3c78f1e3c78f, {0xb94358, 0x1193d40})
        /home/vernon/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20240826095051-d1ddae9379e3/renderers/rasterizer/rasterizer.go:17 +0xef
github.com/aldernero/sketchy.(*Sketch).Draw(0xc000532008, 0xc00087a1c0)
        /home/vernon/go/pkg/mod/github.com/aldernero/sketchy@v0.0.0-20240115184952-6797ab3be9b0/sketch.go:348 +0xb99
github.com/hajimehoshi/ebiten/v2.(*gameForUI).DrawOffscreen(0xc000829650)
        /home/vernon/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.7.10/gameforui.go:152 +0x27
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).drawGame(0xc0005c9680, {0xb9cbb0, 0xc000409c20}, 0x3ff0000000000000?, 0x0)
        /home/vernon/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.7.10/internal/ui/context.go:197 +0x128
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrameImpl(0xc0005c9680, {0xb9cbb0, 0xc000409c20}, 0x1, 0x4090400000000000, 0x408f400000000000, 0x3ff0000000000000, 0xc0001e3608, 0x0)
        /home/vernon/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.7.10/internal/ui/context.go:165 +0x39b
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrame(0xc0005c9680, {0xb9cbb0, 0xc000409c20}, 0x4090400000000000, 0x408f400000000000, 0x3ff0000000000000, 0xc0001e3608)
        /home/vernon/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.7.10/internal/ui/context.go:73 +0x76
github.com/hajimehoshi/ebiten/v2/internal/ui.(*UserInterface).updateGame(0xc0001e3608)
        /home/vernon/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.7.10/internal/ui/ui_glfw.go:1457 +0x1a5
github.com/hajimehoshi/ebiten/v2/internal/ui.(*UserInterface).loopGame(0xc0001e3608)
        /home/vernon/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.7.10/internal/ui/ui_glfw.go:1414 +0x97
github.com/hajimehoshi/ebiten/v2/internal/ui.(*UserInterface).runMultiThread.func2()
        /home/vernon/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.7.10/internal/ui/run.go:67 +0x37
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /home/vernon/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
        /home/vernon/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:75 +0x96
exit status 2
```

**Comment by tdewolff** [comment]
Thanks again Vernon, I will work on a fix!

**Comment by tdewolff** [comment]
Should be fixed now.
